---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: ""
  capacity:
    storage: 0.1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/filename"
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "mydep"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      name: "myweb"
      labels:
        app: myweb
    spec:
      volumes:
        - name: "myweb-pvc"
          persistentVolumeClaim:
            claimName: mypvc
      containers:
        - name: "bitbybit"
          image: vimal13/apache-webserver-php
          volumeMounts:
            - mountPath: /var/www/html
              name: myweb-pvc
            
---
apiVersion: v1
kind: Service
metadata:
  name: mylb
spec:
  selector:
    app: myweb
  type: NodePort
  ports:
    - targetPort: 80
      port: 8080
      nodePort: 30400
 
